spring.application.name=account

spring.datasource.url=jdbc:postgresql://localhost:5432/account_db
spring.datasource.username=account_user
spring.datasource.password=account_pass_123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
