spring.application.name=api-gateway
spring.cloud.gateway.rotes:
  - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/api/accounts/**

        - id: transfer-service
          uri: lb://TRANSFER-SERVICE
          predicates:
            - Path=/api/transfers/**


server.port=8080

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

